import {VEHICLE_BUY_MODE, VehicleListItem} from "./VehicleListItem";
import {
    BIKE_LICENSE,
    BOAT_LICENSE,
    BUS_LICENSE,
    HELICOPTER_LICENSE,
    INDUSTRIAL_LICENSE,
    MILITARY_LICENSE,
    PKW_LICENSE,
    PLANE_LICENSE,
    QUAD_LICENSE,
    STUNT_LICENSE,
    TRUCK_LICENSE
} from "../Licenses/VehicleLicenses/AVehicleLicense";
import {VehicleCategory} from "./VehicleCategories";

export function getVehicleListItemByHash(hash: number): VehicleListItem|false {
    for (const item of VEHICLE_LIST) {
        if (item.hash === hash) return item;
    }
    return false;
}

export function getVehicleListItemByName(name: string): VehicleListItem|false {
    for (const item of VEHICLE_LIST) {
        if (item.displayName === name) return item;
    }
    return false;
}

export const VEHICLE_LIST: VehicleListItem[] = [
    // Bicycle
    new VehicleListItem(600, "bmx", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(450, "cruiser", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(350, "fixter", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(900, "scorcher", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(1500, "tribike", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(1500, "tribike2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),
    new VehicleListItem(1500, "tribike3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bicycle, []),

    // Bike
    new VehicleListItem(15000, "akuma", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(17000, "avarus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(16000, "bagger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "bati", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(25000, "bati2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(5000, "bf400", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(22000, "carbonrs", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "chimera", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(30000, "cliffhanger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(12000, "daemon", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(12000, "daemon2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(14000, "defiler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(-1, "deathbike", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(-1, "deathbike2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(-1, "deathbike3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "diablous", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "diablous2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "double", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(6000, "enduro", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(12000, "esskey", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(3000, "faggio", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, []),
    new VehicleListItem(3000, "faggio2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Bike, []),
    new VehicleListItem(3000, "faggio3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, []),
    new VehicleListItem(10000, "fcr", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(13000, "fcr2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(23000, "gargoyle", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(18000, "hakuchou", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(27000, "hakuchou2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(17000, "hexer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(24000, "innovation", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(20000, "lectro", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(10000, "manchez", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(12000, "nemesis", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(33000, "nightblade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(-1, "oppressor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(-1, "oppressor2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(8000, "pcj", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(12000, "ratbike", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(7000, "ruffian", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(6000, "sanchez", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(7000, "sanchez2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(55000, "sanctus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(2200000, "shotaro", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(30000, "sovereign", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(23000, "thrust", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(15000, "vader", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(19000, "vindicator", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(37000, "vortex", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(28000, "wolfsbane", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(32000, "zombiea", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),
    new VehicleListItem(32000, "zombieb", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bike, [BIKE_LICENSE]),

    //Boats
    new VehicleListItem(70000, "dinghy", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(70000, "dinghy2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(70000, "dinghy3", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(70000, "dinghy4", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(218000, "jetmax", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(195000, "marquis", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(12000, "seashark", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(12000, "seashark2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(12000, "seashark3", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(237000, "speeder", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(237000, "speeder2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(240000, "squalo", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(2300000, "submersible", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(3300000, "submersible2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(35000, "suntrap", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(140000, "toro", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(140000, "toro2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(130000, "tropic", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(130000, "tropic2", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),
    new VehicleListItem(100000, "tug", VEHICLE_BUY_MODE.BOAT_SHOPS, VehicleCategory.Boat, [BOAT_LICENSE]),

    // commercials
    new VehicleListItem(45000, "benson", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(100000, "biff", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "cerberus", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Truck, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "cerberus2", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Truck, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "cerberus3", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Truck, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(35000, "hauler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(34000, "hauler2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(18500, "mule", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(18500, "mule2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(18500, "mule3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "mule4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(115000, "packer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(100000, "phantom", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "phantom2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(100000, "phantom3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(70000, "pounder", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "pounder2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(40000, "stockade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(40000, "stockade3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "terbyte", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),

    // Compacts
    new VehicleListItem(20000, "blista", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(25000, "brioso", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(24000, "dilettante", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(24000, "dilettante2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(20000, "issi2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(-1, "issi3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(-1, "issi4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(-1, "issi5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(-1, "issi6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(10000, "panto", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(18000, "prairie", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),
    new VehicleListItem(8500, "rhapsody", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Compact, [PKW_LICENSE]),

    // Coupes
    new VehicleListItem(120000, "cogcabrio", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(115000, "exemplar", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(100000, "f620", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(115000, "felon", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(105000, "felon2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(55000, "jackal", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(25000, "oracle", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(20000, "oracle2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(35000, "sentinel", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(40000, "sentinel2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(220000, "windsor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(300000, "windsor2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(45000, "zion", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),
    new VehicleListItem(45000, "zion2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Coupes, [PKW_LICENSE]),

    // Emergency
    new VehicleListItem(-1, "ambulance", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "fbi", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "fbi2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "firetruk", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [TRUCK_LICENSE]), // same as firetruck
    new VehicleListItem(-1, "lguard", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "pbus", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [BUS_LICENSE]),
    new VehicleListItem(-1, "police", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "police2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "police3", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "police4", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "policeb", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "polmav", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [HELICOPTER_LICENSE]),
    new VehicleListItem(-1, "policeold1", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "policeold2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "policet", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "pranger", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "predator", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [BOAT_LICENSE]),
    new VehicleListItem(-1, "riot", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "riot2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "sheriff", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),
    new VehicleListItem(-1, "sheriff2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Emergency, [PKW_LICENSE]),

    //Helicopters
    new VehicleListItem(-1, "akula", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(18500, "annihilator", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(1500000, "buzzard", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(2500000, "buzzard2", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3490000, "cargobob", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3490000, "cargobob2", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3590000, "cargobob3", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3490000, "cargobob4", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(800000, "frogger", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(800000, "frogger2", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(80000, "havok", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(13500000, "hunter", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(2700000, "maverick", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(1700000, "savage", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "seasparrow", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(5000000, "skylift", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3400000, "supervolito", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(3500000, "supervolito2", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(5000000, "swift", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(5000000, "swift2", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),
    new VehicleListItem(12000000, "valkyrie", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(12000000, "valkyrie2", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Helicopter, [HELICOPTER_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(6500000, "volatus", VEHICLE_BUY_MODE.FLIGHT_SHOPS, VehicleCategory.Helicopter, [HELICOPTER_LICENSE]),

    // Industrial
    new VehicleListItem(-1, "bulldozer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Industrial, [INDUSTRIAL_LICENSE]),
    new VehicleListItem(-1, "cutter", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Industrial, [INDUSTRIAL_LICENSE]),
    new VehicleListItem(-1, "dump", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Industrial, [INDUSTRIAL_LICENSE, TRUCK_LICENSE]),
    new VehicleListItem(75000, "flatbed", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(100000, "guardian", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "handler", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Industrial, [INDUSTRIAL_LICENSE]),
    new VehicleListItem(-1, "handler", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Industrial, [INDUSTRIAL_LICENSE]),
    new VehicleListItem(90000, "mixer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Industrial, [TRUCK_LICENSE]),
    new VehicleListItem(90000, "mixer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Industrial, [TRUCK_LICENSE]),
    new VehicleListItem(170000, "rubble", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Industrial, [TRUCK_LICENSE]),
    new VehicleListItem(130000, "tiptruck", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Industrial, [TRUCK_LICENSE]),
    new VehicleListItem(110000, "tiptruck2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Industrial, [TRUCK_LICENSE]),

    // Millitary
    new VehicleListItem(-1, "apc", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [MILITARY_LICENSE]),
    new VehicleListItem(-1, "barracks", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "barracks2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "barracks3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "barrage", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "chernobog", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "crusader", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "halftrack", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [TRUCK_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "khanjali", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [MILITARY_LICENSE]),
    new VehicleListItem(-1, "rhino", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Military, [MILITARY_LICENSE]),
    new VehicleListItem(-1, "scarab", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Military, [MILITARY_LICENSE, PKW_LICENSE]),
    new VehicleListItem(-1, "scarab2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Military, [MILITARY_LICENSE, PKW_LICENSE]),
    new VehicleListItem(-1, "scarab3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Military, [MILITARY_LICENSE, PKW_LICENSE]),
    new VehicleListItem(-1, "thruster", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Military, [HELICOPTER_LICENSE]), // JETPACK !?
    new VehicleListItem(-1, "trailersmall2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, [MILITARY_LICENSE]), // Luftabwehtrailer

    // muscle
    new VehicleListItem(20000, "blade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(19000, "buccaneer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "buccaneer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(18000, "chino", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "chino2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "clique", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "coquette3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "deviant", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "dominator", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(36000, "dominator2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "dominator3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "dominator4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "dominator5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "dominator6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(21000, "dukes", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "dukes2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(18000, "faction", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "faction2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(40000, "faction3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(22000, "gauntlet", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(23000, "gauntlet2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "hermes", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(40000, "hotknife", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "impaler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "impaler2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "impaler3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "impaler4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "imperator", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "imperator2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "imperator3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(130000, "lurcher", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(10000, "moonbeam", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "moonbeam2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(23000, "nightshade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(24000, "phoenix", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(15000, "picador", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(12000, "ratloader", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(12000, "ratloader2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(19000, "ruiner", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(25000, "ruiner2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "ruiner3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(17000, "sabregt", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "sabregt2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(29000, "slamvan", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(30000, "slamvan2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(31000, "slamvan3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "slamvan4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "slamvan5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "slamvan6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(19000, "stalion", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(20000, "stalion2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(23000, "tampa", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "tampa3", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Muscles, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "tulip", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "vamos", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(16000, "vigero", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(18000, "virgo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(35000, "virgo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(36000, "virgo3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(20000, "voodoo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(15000, "voodoo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),
    new VehicleListItem(-1, "yosemite", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Muscles, [PKW_LICENSE]),

    // Off-road
    new VehicleListItem(5500, "bfinjection", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(17500, "bifta", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "blazer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [QUAD_LICENSE]),
    new VehicleListItem(-1, "blazer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [QUAD_LICENSE]),
    new VehicleListItem(-1, "blazer3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [QUAD_LICENSE]),
    new VehicleListItem(-1, "blazer4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [QUAD_LICENSE]),
    new VehicleListItem(-1, "blazer5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [QUAD_LICENSE]),
    new VehicleListItem(12500, "bodhi2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(100000, "brawler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "bruiser", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "bruiser2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "bruiser3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(10000, "dloader", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "dubsta3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(250000, "dune", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(450000, "dune2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "dune3", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "dune4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "dune5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "freecrawler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "insurgent", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(5000000, "insurgent2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "insurgent3", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(18000, "kalahari", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "marshall", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, TRUCK_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(100000, "mesa3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "monster", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, TRUCK_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "monster3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, TRUCK_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "monster4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, TRUCK_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "monster5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Stunt, [PKW_LICENSE, TRUCK_LICENSE, STUNT_LICENSE]),
    new VehicleListItem(-1, "menacer", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(2500000, "nightshark", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(10000, "rancherxl", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(10000, "rancherxl2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(5000, "rebel", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(8000, "rebel2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "rcbandito", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Other, []),
    new VehicleListItem(-1, "riata", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(30000, "sandking", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(25000, "sandking2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(-1, "technical", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "technical2", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "technical3", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Offroad, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(500000, "trophytruck", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),
    new VehicleListItem(500000, "trophytruck2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Offroad, [PKW_LICENSE]),

    // PLANES
    new VehicleListItem(-1, "alphaz1", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "avenger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "besra", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "blimp", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE, HELICOPTER_LICENSE]),
    new VehicleListItem(-1, "blimp2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE, HELICOPTER_LICENSE]),
    new VehicleListItem(-1, "blimp3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE, HELICOPTER_LICENSE]),
    new VehicleListItem(-1, "blimp3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "bombushka", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "cargoplane", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "cuban800", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "dodo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "duster", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "howard", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "hydra", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "jet", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "lazer", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "luxor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "luxor2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "mammatus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "microlight", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "miljet", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "mogul", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "molotok", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "nimbus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "nokota", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "pyro", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "rogue", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "seabreeze", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "shamal", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "starling", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "strikeforce", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "stunt", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "titan", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "tula", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "velum", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "velum2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "vestra", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Plane, [PLANE_LICENSE]),
    new VehicleListItem(-1, "volatol", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Plane, [PLANE_LICENSE, MILITARY_LICENSE]),

    // SUVs
    new VehicleListItem(-1, "baller", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "baller2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "baller3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "baller4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "baller5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "baller6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "bjxl", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "cavalcade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "cavalcade2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "contender", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "dubsta", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "dubsta2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "fq2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "granger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "gresley", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "habanero", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "huntley", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "landstalker", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(40000, "mesa", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(40000, "mesa2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "patriot", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "patriot2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "radi", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "rocoto", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "seminole", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "serrano", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "toros", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "xls", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "xls2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),

    // Sedans
    new VehicleListItem(-1, "asea", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "asea2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "asterope", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "cog55", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "cog552", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "cognoscenti", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "cognoscenti2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "emperor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "emperor2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "emperor3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "fugitive", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "glendale", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "ingot", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "intruder", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "limo2", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Sedans, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "premier", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "primo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "primo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "regina", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "romero", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "schafter2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "schafter5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "schafter6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "stafford", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "stanier", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "stratum", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "stretch", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "superd", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "surge", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "tailgater", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "warrener", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),
    new VehicleListItem(-1, "washington", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sedans, [PKW_LICENSE]),

    // Service
    new VehicleListItem(180000, "airbus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(-1, "brickade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(180000, "bus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(250000, "coach", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(-1, "pbus2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(-1, "rallytruck", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(131000, "rentalbus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(-1, "taxi", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Other, [PKW_LICENSE]),
    new VehicleListItem(131000, "tourbus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Bus, [BUS_LICENSE]),
    new VehicleListItem(-1, "trash", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "trash2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "wastelander", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),

    // Sport
    new VehicleListItem(-1, "alpha", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "banshee", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "bestiagts", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(10000, "blista2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(10000, "blista3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "buffalo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "buffalo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "buffalo3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "carbonizzare", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "comet2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "comet3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "comet4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "coquette", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "deveste", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "elegy", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "elegy2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "feltzer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "furoregt", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "fusilade", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "futo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "hotring", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "infernus2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "italigto", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "jester", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "jester2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "khamelion", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "kuruma", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "kuruma2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "lynx", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "massacro", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "massacro2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "neon", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "ninef", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "ninef2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "omnis", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "pariah", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "penumbra", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "raiden", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "rapidgt", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "rapidgt2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "raptor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "revolter", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "ruston", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "schafter3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "schafter4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "schlagen", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "schwarzer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "sentinel3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "seven70", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "specter", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "specter2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "streiter", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "sultan", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "surano", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "tampa2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "tropos", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "verlierer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "zr380", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "zr3802", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),
    new VehicleListItem(-1, "zr3803", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Sport, [PKW_LICENSE]),

    // Classics
    new VehicleListItem(-1, "ardent", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "btype", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "btype2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "btype3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "casco", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "cheetah2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "coquette2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "deluxo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "feltzer3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "gt500", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "infernus2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "jb700", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "mamba", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "manana", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "monroe", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "peyote", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "pigalle", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "rapidgt3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "retinue", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "savestra", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "stinger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "stingergt", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "stromberg", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "swinger", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "torero", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "tornado6", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "turismo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "viseris", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),
    new VehicleListItem(-1, "ztype", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Classic, [PKW_LICENSE]),

    // super
    new VehicleListItem(-1, "adder", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "autarch", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "banshee2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "bullet", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "cheetah", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "cyclone", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "entityxf", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "fmj", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "gp1", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "infernus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "italigtb", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "italigtb2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "le7b", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "nero", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "nero2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "osiris", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "penetrator", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "pfister811", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "prototipo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "reaper", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "sc1", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "scramjet", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "sheava", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "sultanrs", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "t20", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "tempesta", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "turismor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "tyrus", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "vacca", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "vagner", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "vigilante", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "visione", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "voltic", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "voltic2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "xa21", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),
    new VehicleListItem(-1, "zentorno", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SuperSport, [PKW_LICENSE]),

    // Trailer
    new VehicleListItem(-1, "armytanker", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "armytrailer2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "baletrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "boattrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "cablecar", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "docktrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "graintrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "proptrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "raketrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tr2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tr3", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tr4", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trflat", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tvtrailer", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tanker", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "tanker2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trailerlogs", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trailersmall", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trailers", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trailers2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),
    new VehicleListItem(-1, "trailers3", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Trailer, []),

    // Trains
    new VehicleListItem(-1, "freight", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),
    new VehicleListItem(-1, "freightcar", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),
    new VehicleListItem(-1, "freightcont1", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),
    new VehicleListItem(-1, "freightcont2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),
    new VehicleListItem(-1, "freightgrain", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),
    new VehicleListItem(-1, "tankercar", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Train, []),

    // Utility
    new VehicleListItem(-1, "airtug", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "caddy", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "caddy2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "caddy3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "docktug", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "forklift", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "mower", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "ripley", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "sadler", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(30000, "sadler2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "scrap", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "towtruck", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "towtruck2", VEHICLE_BUY_MODE.NOT_BUYABLE, VehicleCategory.Truck, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "tractor", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "tractor2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "tractor3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [PKW_LICENSE]),
    new VehicleListItem(-1, "utillitruck", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "utillitruck2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Utility, [TRUCK_LICENSE]),
    new VehicleListItem(-1, "utillitruck3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),

    // Vans
    new VehicleListItem(-1, "bison", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "bison2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "bison3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "bobcatxl", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.SUV, [PKW_LICENSE]),
    new VehicleListItem(-1, "boxville", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "boxville2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "boxville3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "boxville4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "boxville5", VEHICLE_BUY_MODE.BLACKMARKET, VehicleCategory.Van, [PKW_LICENSE, MILITARY_LICENSE]),
    new VehicleListItem(-1, "burrito", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "burrito2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "burrito3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "burrito4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "burrito5", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "camper", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "gburrito", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "gburrito2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "journey", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "minivan", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "minivan2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "paradise", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "pony", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "pony2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "rumpo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "rumpo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "rumpo3", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "speedo", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "speedo2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "speedo4", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "surfer", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "surfer2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "taco", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "youga", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE]),
    new VehicleListItem(-1, "youga2", VEHICLE_BUY_MODE.VEHICLE_SHOPS, VehicleCategory.Van, [PKW_LICENSE])
];
