import {ShopType} from "./Shop/ShopPosition";

export enum VehicleCategory {
    Bicycle = "Bicycle",
    Bike = "Bike",
    Boat = "Boat",
    Bus = "Bus",
    Classic = "Classic",
    Compact = "Compact",
    Coupes = "Coupes",
    Muscles = "Muscles",
    Offroad = "Offroad",
    Sedans = "Sedans",
    Sport = "Sport",
    SuperSport = "SuperSport",
    SUV = "SUV",
    Truck = "Truck",
    Utility = "Utility",
    Van = "Van",
    Plane = "Plane",
    Helicopter = "Helicopter",
    Trailer = "Trailer",
    Quad = "Quad",
    Military = "Military",
    Stunt = "Stunt",
    Emergency = "Emergency",
    Industrial = "Industrial",
    Other = "Other",
    Train = "Train"
}
